version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=capstone.news_settings
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  cms: 
    build: .
    command: python manage.py runserver 0.0.0.0:8001 --settings=capstone.cms_settings
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    env_file:
      - .env
      