# Generated by Django 4.2.5 on 2024-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_article_byline_article_byline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(max_length=2000, upload_to="static/news/images"),
        ),
    ]
