# Generated by Django 4.2.5 on 2024-06-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=2000, upload_to="static/news/images"),
                ),
                ("caption", models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="article", name="image",),
        migrations.AddField(
            model_name="article",
            name="main",
            field=models.ManyToManyField(to="news.image"),
        ),
    ]
