# Generated by Django 4.2.5 on 2024-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_image_remove_article_image_article_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=2000, upload_to="news/static/news/images"
            ),
        ),
    ]
