# Generated by Django 4.2.5 on 2024-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_image_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hero_priority",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="article",
            name="is_hero",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(max_length=2000, upload_to="static/news/images"),
        ),
    ]
