# Generated by Django 4.2.5 on 2024-07-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_hero_priority_article_is_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='url_name',
            field=models.SlugField(default='default-url', unique=True),
        ),
    ]
