# Generated by Django 4.2.5 on 2024-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_section_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url_name',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
