# Generated by Django 4.2.5 on 2024-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_section_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(max_length=20)),
                ('sub_url_name', models.SlugField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_sections',
            field=models.ManyToManyField(to='news.subsection'),
        ),
    ]
