# Generated by Django 4.2.5 on 2024-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_subsection_article_updated_at_section_sub_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='url_name',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_url_name',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='sub_url_name',
            field=models.URLField(max_length=20, null=True),
        ),
    ]
