# Generated by Django 4.2.5 on 2024-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_article_url_alter_subsection_sub_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sub_sections',
            field=models.ManyToManyField(null=True, to='news.subsection'),
        ),
    ]
