# Generated by Django 4.2.5 on 2024-07-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.AlterField(
            model_name='section',
            name='section_url_name',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.section'),
        ),
    ]
