# Generated by Django 4.2.5 on 2024-07-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_remove_article_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main',
        ),
        migrations.AddField(
            model_name='article',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.image'),
        ),
    ]
