# Generated by Django 4.2.5 on 2024-08-06 16:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_remove_article_main_article_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
