# Generated by Django 4.2.5 on 2024-08-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_article_content_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.section'),
        ),
    ]
