# Generated by Django 4.2.5 on 2024-08-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_remove_author_author_author_name_author_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='byline',
        ),
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.author'),
        ),
    ]
