# Generated by Django 4.2.5 on 2024-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_rename_name_author_byline_alter_article_byline'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
