# Generated by Django 4.2.5 on 2024-08-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='user_followed',
        ),
        migrations.AddField(
            model_name='following',
            name='author_followed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_followed', to='news.author'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user_following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
