# Generated by Django 4.2.5 on 2024-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hero_priority',
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
