# Generated by Django 4.2.5 on 2024-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
