# Generated by Django 4.2.5 on 2024-09-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='article_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='comment_liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked', to='news.comment'),
        ),
    ]
