# Generated by Django 4.2.5 on 2024-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
