# Generated by Django 4.2.5 on 2024-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_article_changed_by_historicalarticle_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_hero',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='is_featured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='is_hero',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
