# Generated by Django 4.2.5 on 2024-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('featured_articles', models.ManyToManyField(related_name='featured_articles', to='news.article')),
                ('hero_articles', models.ManyToManyField(related_name='hero_articles', to='news.article')),
            ],
        ),
    ]
