# Generated by Django 4.2.5 on 2024-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomepageContent',
            new_name='Homepage',
        ),
    ]
