# Generated by Django 4.2.5 on 2024-08-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_homepagecontent_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='headline',
        ),
    ]
