# Generated by Django 4.2.5 on 2024-08-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
        ('cms', '0004_homepage_featured_404_homepage_featured_electric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_404',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_err',
            field=models.ManyToManyField(blank=True, related_name='featured_err', to='news.article'),
        ),
    ]
