# Generated by Django 4.2.5 on 2024-08-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
        ('cms', '0005_remove_homepage_featured_404_homepage_featured_err'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_err',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_404',
            field=models.ManyToManyField(related_name='featured_404', to='news.article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_electric',
            field=models.ManyToManyField(related_name='featured_electric', to='news.article'),
        ),
    ]
