# Generated by Django 4.2.5 on 2024-08-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_article_hero_priority_article_is_featured'),
        ('cms', '0007_remove_homepage_hero_articles_homepage_hero_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_404',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_homepage', to='news.section'),
        ),
    ]
