# Generated by Django 4.2.5 on 2024-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_rename_hero_article_homepage_hero_articles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_articles',
            new_name='hero_article',
        ),
    ]
